apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-03-05T19:07:10Z"
  name: carts-canary
  resourceVersion: "15419"
  selfLink: /api/v1/namespaces/sockshop-production/services/carts
  uid: 83fe1e7f-5f14-11ea-8ebc-42010ab40fe9
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
